input AuthLoginInput {
  email: String
  password: String
}

type AuthLoginOutput {
  token: String
  username: String
}

extend type Mutation {
  authLogin(input: AuthLoginInput): AuthLoginOutput!
}
