
name: CI - Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: "Start: Unit Testing"
      run: |
        yarn install
        yarn test:server
  lint_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    - uses: DeLaGuardo/setup-clojure@7.0
      with:
        cli: 1.10.1.693       # Clojure CLI based on tools.deps
        lein: 2.9.1           # Leiningen
        boot: 2.8.3           # Boot.clj
        bb: 0.7.8             # Babashka
        clj-kondo: 2022.05.31 # Clj-kondo
        cljstyle: 0.15.0      # cljstyle
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: "Start: Linter"
      run: |
        yarn install
        yarn lint:server
  test_unit_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.3'
    - name: "Start: Unit Testing"
      run: |
        yarn install
        yarn test:unit:app
  release_app_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
    - name: "Start: Deploy Web Preview"
      run: |
        yarn install
        yarn deploy:web:preview:app
  lint_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
    - name: "Start: Linter"
      run: |
        yarn install
        yarn app install:deps
        yarn lint:app

